### ISSUE TITLE
Aliases can be dict (map of strings) OR list of them

### ISSUE THREAD

**Issue by vsoch** [autamus/binoc#5]
I think binoc is hiccuping on recipes that look like this:
```yaml
aliases:
  - name: run-notebook
    command: jupyter notebook --no-browser --port=$(shuf -i 2000-65000 -n 1) --ip 0.0.0.0
    options: --home ${HOME} --bind ${HOME}/.local:/home/joyvan/.local
```
which is a long handed way of writing:

```yaml
aliases:
  run-notebook: jupyter notebook --no-browser --port=$(shuf -i 2000-65000 -n 1) --ip 0.0.0.0
```
but adds options.

The struct is defined here:

https://github.com/autamus/binoc/blob/3323526ff05947170af92f366a7b3ce39f3b3ac1/parsers/shpc.go#L48

and the error looks like:

```
Parse Error: Couldn't Read --> /github/workspace/registry/jupyter/datascience-notebook/container.yaml
Error: yaml: unmarshal errors:
  line 12: cannot unmarshal !!seq into map[string]string
```
so that's my suspicion!
